name: Fetch localization data from dotabuff/d2vpkr

on:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2

      - name: Install packages
        run: pip install vdf

      - name: Fetch localization data
        run: python ./scripts/pull.py

      - name: Fetch version data
        run: python ./scripts/version.py

      - name: Commit and Push
        run: |
          git config user.name "Nihongoka Bot"
          git config user.email "71134725+nihongoka-bot@users.noreply.github.com"
          git remote set-url origin https://nihongoka-bot:${{ secrets.BOT_GITHUB_TOKEN }}@github.com/nihongoka/dota2
          git add .
          git pull
          git diff-index --quiet HEAD || git commit -m "Client version: $(<version)"
          git push origin master
