name: Release localization data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  release:
    name: Build and compare hash
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(TZ=UTC date +'%Y-%m-%d')"

      - uses: actions/checkout@v2
        with:
          ref: 'master'

      - uses: actions/setup-python@v2

      - name: Install packages
        run: pip install vpk

      - name: Build zip file
        run: python scripts/python/build.py

      - id: new_hash
        run: echo "::set-output name=hash::`md5sum dota2jp.zip | cut -d ' ' -f 1`"

      - id: old_hash
        run: echo "::set-output name=hash::`curl -sL https://github.com/nihongoka/dota2/releases/download/latest/dota2jp.zip | md5sum | cut -d ' ' -f 1`"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: steps.new_hash.outputs.hash != steps.old_hash.outputs.hash
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        with:
          files: ./dota2jp.zip
          tag_name: v${{ steps.date.outputs.date }}

