name: Release localization data

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(TZ=UTC date +'%Y-%m-%d')"

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install packages
        run: pip install vpk

      - name: Build zip file
        run: python scripts/build.py

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        with:
          files: ./dota2jp.zip
          tag_name: v${{ steps.date.outputs.date }}

