name: Translate (On Update)

on:
  push:
    paths:
      - 'main/resource/localization/abilities_english.txt.json'
  schedule:
    - cron: '0 15 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Run translation for diff
        id: run_translate
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BEFORE_SHA: ${{ github.event.before }}
        run: |
          set -e
          EN='main/resource/localization/abilities_english.txt.json'
          JA='main/resource/localization/abilities_japanese.txt.json'
          python scripts/python/translate_diff_ai.py \
            --english "$EN" \
            --japanese "$JA" \
            --commit-range "${BEFORE_SHA:-HEAD^}..${GITHUB_SHA}"
          echo "changes<<EOF" >> "$GITHUB_OUTPUT"
          if [ -f translation_changes.json ]; then
            cat translation_changes.json >> "$GITHUB_OUTPUT"
          else
            echo "[]" >> "$GITHUB_OUTPUT"
          fi
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ai/translate/abilities-${{ github.run_id }}
          title: 'AI翻訳: abilities の差分更新'
          body: |
            自動生成: `abilities_english.txt.json` の更新を検知。

            変更サマリ:

            ```json
            ${{ steps.run_translate.outputs.changes }}
            ```
          add-paths: |
            main/resource/localization/abilities_japanese.txt.json
            translation_changes.json
          labels: |
            translate
            automated

